export function collapse(mode) {}
export function to(index) {}
export function toEnd(ofChar) {}
export function toLine() {}
export function toLineEnd() {}
export function toLineStart() {}
export function toStart(ofChar) {}
export function toTag() {}
export function toWord() {}
